language: node_js

stages:
  - release

notifications:
  email: false

jobs:
  include:
    - stage: release
      node_js: 10.0.0
      before_script:
        - npm run lint
      script:
        - npm run test
        - npm run test:coverage
      after_success:
        - npm run test:report
        - npm run semantic-release
