language: node_js

stages:
  - lint
  - test
  - release

notifications:
  email: false

jobs:
  include:
    - stage: lint
      node_js: 10.0.0
      script:
        - npm run lint

    - stage: test
      node_js: 10.0.0
      script:
        - npm run test
        - npm run test:coverage

    - stage: release
      node_js: 10.0.0
      script:
        - npm run test:report
        - npm run semantic-release
